const api_url_base = "https://ij1tbqacxd.execute-api.us-east-1.amazonaws.com/"
const api_url_getversion = api_url_base + "getversion"
const api_url_getgame = api_url_base + "getgame"
const api_url_submitplayer = api_url_base + "submitplayer"
const api_url_submitwords = api_url_base + "submitwords"
